# This is a basic workflow to build and upload Webchat to S3 bucket with Github Actions

name: South Africa Staging release

# Controls when the action will run.
on:
  workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    with:
      account-sid: /staging/twilio/ZA/account_sid
      environment: staging
      build-env: za-staging
      aws-s3-bucket: tl-public-chat-za-stg