# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: Webchat Dev Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      # Create and fill secret.ts
      - name: Create secret.ts
        run: |
          touch ./private/secret.ts
      - name: Fill secret.ts
        run: |
          cat <<EOT >> ./private/secret.ts
          export const API_KEY = '${{ secrets.IP_FIND_API_KEY }}';
          export const SERVERLESS_URL = '${{ secrets.DEV_SERVERLESS_URL }}';
          EOT
      # Run a single command using the runners shell to install dependencies 
      - name: Install dependencies
        run: npm ci
      # Get the blockedIps for this account
      - name: Get blockedIps
        run: curl -o ./src/blockedIps.json https://tl-public-chat-as-dev.s3.amazonaws.com/blockedIps.json
        shell: bash
      # Build and compile Webchat
      - name: Run build command
        run: CONFIG=as-development npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create secret.ts
        run: |
          touch ./private/secret.ts
      - name: Install dependencies
        run: npm install eslint
      # Run linting
      - name: Run ESLint
        run: npm run lint --if-present
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test